### ISSUE TITLE
Remove "Brave Search" nav option from header

### ISSUE THREAD

**Issue by lukaslevert** [brave/ads-ui#1087]
Unfortunately, we are receiving too many requests from ineligible brands on ads.brave.com/search, presumably because of how easy it is to navigate to that page and book a meeting through Google Calendar.

We'd like to keep the page available so that sales and account managers can send the direct link to more eligible prospects, as the ease of scheduling the time is crucial for that part of the sales journey.

This page will remain discoverable in the ads UI when customers go to select an ad type and see Search unavailable in ads manager. We will monitor responses to see if this should also be pointed elsewhere.

**Task: Remove "Brave Search" navigation option from header**
<img width="354" alt="image" src="https://github.com/brave/ads-ui/assets/79997955/59e42616-bd3e-44ba-b4ed-f9828802b5c3">

**Comment by lukemulks** [comment]
Can you be more specific on the inbound? 

If JP has a list for the sellers that they're prospecting, we should be able to export the list and filter any search advertisers that aren't on that list. 

Any advertiser that isn't on the list is in a cohort we can reach back out to as eligibility widens over time. Becomes a waitlist, and submission response/confirmation should include language stating advertisers will be reviewed for eligibility, and we will be contacted when eligible. 

The Search navigation button URL could also be updated to include a parameter in the URL string that we could filter inbound by. 

We should definitely keep it in both places and modify the logistical process so we don't lose a cohort of interested but unqualified potential customers. This list is one we can approach for early tests, etc. 

Where does the inbound go for submissions, and where do report exports for those submissions live? We should be able to filter for eligibility and solve this near term problem. 

for example: foo.com?source=sales or foo.com?source=website

**Comment by lukaslevert** [comment]
If you follow the landing page CTA (suggest you do to see the flow), you'll be able to pick a time slot to book a meeting. The intent was that interested advertisers could select a time to book a meeting, and either Colin or JP picks up the meeting to discuss search campaign setup/eligibility. 

What has become clear is that making this calendar booking open to anyone is a bad idea. 99% don't qualify, so it's just a burden on time to manually cancel all the meetings that come through. To make sure the intent isn't wasted, we have been directing these people to News and Notifications via a meeting cancellation message:

```
Hello,

We are currently only accepting meetings with brands that meet a minimum relevant keyword volume on Brave Search. After reviewing your booking, we regret to inform you that your business currently does not meet the criteria for the free 30-day Brave Search Ads trial.

We hope to offer Search Ads more broadly in the future. Meanwhile, we encourage you to explore other PPC/CPC advertising opportunities through Brave Ads Manager by signing up at https://ads.brave.com/register.

Should you have any questions or need further assistance, please don't hesitate to reply to this email.

Best regards.
```

The short term solution to this calendar is to simply hide it. We still want it to be available as a live web page to be used as a second step following an initial sales call. But that's a duct tape solution. JP and I are working with Graham and Ian on this as part of Ads Manager. The objective is to qualify advertisers and capture their emails (with opt in of course) for the Brave Ads Newsletter, so that as we expand eligibility, we can update our newsletter audience at each major milestone. It's in the works, and this a step towards that.
