### ISSUE TITLE
Refine copy on "complete account" screen

### ISSUE THREAD

**Issue by lukaslevert** [brave/ads-ui#1088]
Once a customer has signed up for ads.brave.com, they are met with a "welcome" screen prompting their billing details and agreement of several disclaimers that are currently very verbose.

Separately, there's a need to add a disclaimer for supported languages that ad ops is requesting be put on the main landing page, however marketing strongly advises against this as it's not a best practice for acquisition and leads to homepage bloating that distracts and/or detracts from sign-ups that are crucial for email marketing.

To solve both these issues, I propose updating the copy on the "welcome" screen, and adding one for the language. Additionally, at the same time we do this, we (I) should add a page to ads-help.brave.com for "supported languages" which will be linked and updated over time with this disclaimer.

**Here is the proposed copy:**

Please review and agree to the following disclaimers and policies to continue:

[] I understand that first-party analytics are necessary for independent reporting. [Learn more](https://ads-help.brave.com/campaign-performance/reporting)
[] I understand that I can only run ad campaigns in English, Spanish, and Portuguese.
[] I understand that payment is required before campaigns can be launched. [Learn more](https://ads-help.brave.com/campaign-performance/reporting)

[] I have reviewed and agree to the [Advertiser Privacy Policy](https://brave.com/advertiser-privacy/) and [Terms of Service](https://basicattentiontoken.org/advertiser-terms-of-service/) applicable to Brave Ads.

CC @tackley @IanKrieger @lukemulks @murphyd

**Comment by lukaslevert** [comment]
Here's a mock for the above solution: 
<img width="1184" alt="image" src="https://github.com/brave/ads-ui/assets/79997955/365ab30e-a1bc-4032-966a-84890ee31376">

**Comment by murphyd** [comment]
This looks good, thanks @lukaslevert. 
cc: @lukemulks
