### ISSUE TITLE
Remember report settings

### ISSUE THREAD

**Issue by IanKrieger** [brave/ads-ui#1227]
As a user, I want reporting to “remember” the view that I set in the previous visit, instead of going back to the default view every time I log in or refresh my browser

**Comment by murphyd** [comment]
Did I duplicate this? https://github.com/brave/ads-admin-dashboard/issues/1752 😄

**Comment by IanKrieger** [comment]
I think that would be for the admin dashboard, not the user facing one so we'll keep it!
