### ISSUE TITLE
Update image on ads.brave.com/search

### ISSUE THREAD

**Issue by lukaslevert** [brave/ads-ui#1230]
As discussed with @rmcfadden3, the current images still say "beta". For simplicity sake, it's probably ok to revert to a static image for the time being. See new image below:

![New image for Search](https://github.com/brave/ads-ui/assets/79997955/953c52e9-95f7-4509-89c7-1156d6bd67b8)

**Comment by rmcfadden3** [comment]
lgtm!

**Comment by lukaslevert** [comment]
@IanKrieger if it doesn't suit the page and looks off, we can return to a carousel, perhaps. Just want to keep things simple with these pages as I don't think we'll be maintaining them in the long run.

**Comment by IanKrieger** [comment]
Closing in favor of: https://github.com/brave/ads-ui/issues/1296
