### ISSUE TITLE
Campaign analytics improvements 

### ISSUE THREAD

**Issue by dlipeles** [brave/ads-ui#189]
With new confirmation types and data coming in we will want to reflect these in the analytics. 
Adding items to this issue until everything is accounted and planned for :

- Via Clayton, on the monthly chart we can use the full date MM DD YYYY as it will be easier for advertisers to read.
- Via Clayton, we should make the boxes in the numbers more distinct from the charts, or have seperate range controls for chart and boxes. 

![Image from iOS](https://user-images.githubusercontent.com/4713771/68633169-dd38b580-04be-11ea-8811-9b1031b2ca6a.png)

**Comment by IanKrieger** [comment]
Closing
