### ISSUE TITLE
Campaign Creator: Lifetime Budget: USD amount populates as BAT

### ISSUE THREAD

**Issue by lukemulks** [brave/ads-ui#261]
In the new Campaign Creator, when I input the Lifetime Budget value into the form field, with USD selected as the denomination, the budget value appears to only denominate in BAT. 

To reproduce: 
- Create a new Campaign in the Campaign Creator
- Input the Lifetime Budget Value with the denomination selected as USD 
- Observe the Lifetime Value as denominated in BAT

Expected behavior: 
- If USD is selected as the denomination, the value that the advertiser inputs should denominate in USD. 

Screenshot
![Screenshot from 2020-02-29 13-41-35](https://user-images.githubusercontent.com/8979240/75615497-39b8f280-5af9-11ea-8ba5-ac56cf355365.png)

I've tried a couple different things to try and force the value to update to USD, including: 
- Toggling the denomination to BAT, inputting the value, then switching the denomination to USD
- Inputting the budget, selecting BAT, then switching back to USD

Neither of those approaches resolved. 

What I can do as a workaround, is setup in the Campaign Creator so I can target at the platform/OS level, and then modify via the Admin Campaign Creator, since I have the ability to override the denomination from those campaign settings. 

This is one I would definitely prioritize in advance of any client-facing operations. 

@dlipeles @jsecretan

**Comment by PedroFonsecaDEV** [comment]
Hi, @dlipeles Hope you are doing well.

I would like to give a try on this issue, if possible.  

Thanks.

**Comment by dlipeles** [comment]
Hi @PedroFonsecaDEV , thank you so much for you interest in our repo, we have solved this particular issue but I will try to update our issues over the next weeks to better reflect which ones are really open. 

Thank you again for your enthusiasm towards Brave!

**Comment by PedroFonsecaDEV** [comment]
@dlipeles No problem, thanks for the update.  I'd love to get involved in the project.  If you can guide me toward some issues that would be better I'd appreciate it.
