### ISSUE TITLE
Entering http instead of https issues error, doesn't allow re-saving, doesn't highlight error

### ISSUE THREAD

**Issue by murphyd** [brave/ads-ui#273]
When entering a non-https URL and clicking "Save" at the bottom, the button says "Saving..." but doesn't look like it's doing anything. Eventually the following message appears at the top:
![image](https://user-images.githubusercontent.com/4502617/76469148-08c3a200-63c4-11ea-8b3a-724824053ecd.png)

However, I do not see a red highlight showing the error. In addition, the save button continues to say "Saving..." and doesn't allow an attempt to save again.

To get this working again, the page needs to be refreshed which blanks all fields.

**Comment by IanKrieger** [comment]
Should be resolved
