### ISSUE TITLE
"Save + Add New" button for creating creatives

### ISSUE THREAD

**Issue by murphyd** [brave/ads-ui#275]
When adding multiple creatives, we need to press "Save" to save the present creative, click back, then enter the next creative.

Would it be possible to leave the save button, but add a "Save, Add New" button to the right of it which would allow the present creative to be saved, then open a new creative page to start a new one?
![image](https://user-images.githubusercontent.com/4502617/76469886-9bb10c00-63c5-11ea-9e17-83acb521840e.png)
This should open at the top of the page too (versus reloading and opening at the bottom) so the user can easily begin inputting the next creative without having to scroll up.

Additional idea: After it saves and opens a new creative screen,  perhaps a confirmation dialog box that says "[previous creative name] saved successfully" so it doesn't seem as if the page refreshed but didn't save any data.

**Comment by IanKrieger** [comment]
No longer relevant in current flow
