### ISSUE TITLE
Refactor ads-ui and improve maintainability 

### ISSUE THREAD

**Issue by dlipeles** [brave/ads-ui#304]
As we begin to onboard a greater number of users, maintainability of the codebase will be key. 

Steps we should take: 

- [x] Port admin code to github.com/brave/admin-ads-manager
- [ ] Remove admin code from ads-ui
- [ ] Rename ads-ui => ads-manager
- [x] Set up readme on ads-manager repo
- [ ] Remove redux from user-side, we want to use apollo graphQL here 
- [ ] Before making major integrations with apollo-graphQL ensure in browser caching works properly
- [ ] Remove as much boiler plate from root directory as possible
`rm` /actions folder, store.ts, index.tsx, index.css, react-app-env.d.ts, containers, /state,

**Comment by IanKrieger** [comment]
Completed
