### ISSUE TITLE
Campaign-Builder/Advertiser/Creative-Details: Update “in-page image” to “display banner”

### ISSUE THREAD

**Issue by lukemulks** [brave/ads-ui#312]
In the Creative Details UI, Publisher Ads are currently named “In-Page Images” 

![2C48D93C-A430-47A9-9CDE-F37A64E49281](https://user-images.githubusercontent.com/8979240/77834113-59930480-70ff-11ea-8322-632545e0561e.png)
![A699440B-9F6D-4F25-8930-1078642B65C6](https://user-images.githubusercontent.com/8979240/77834114-5bf55e80-70ff-11ea-8e0e-2fef84caae14.png)

If I’m reading between the tea leaves for the potential logic behind the name choice, I suspect that “In-Page Images” was likely chosen to: 

A. provide with some versatility beyond classifying explicitly as “Publisher Ads”, for both the ability to place the image in locations other than “publisher” domains in the traditional sense (for example: inject banners in-situ in creator pages on YT, and in e-commerce, etc.) 

and 

B. to potentially allow opportunity for additional “publisher” creative types (example: video, text, native, in-banner video, rich media, audio, etc.). 

However, there are some potentially avoidable issues and/or friction points with “in-page images” as the creative name that we could get ahead of prior to releasing self-serve to the general public:

- “in-page image” is a not a standardized or well-known name for display ads in the industry (the people that will be customers, or inconsistent with other platforms that more casual customers will be also be likely to be using) 

- the deviation becomes a question mark, even though the current name is relatively intuitive. There is a lot of learning required by advertisers with how our platform and ecosystem function and flow, so deviating from norms in this area brings complexity and potential for confusion when we should be aiming for easy wins and to reduce any excess cognitive load friction within new self-serve customer ui wherever possible (just my personal view)

I propose we change the current “In-Page Image” name to “display banner” 

- display banner is a semi-standardized/normative name used for the creative type in the industry (for example: “IAB standard display banners”)

- “banner” is typically the parent-name for the unit (read this as “the square or rectangle”) in-page. There are different media types that run within banner units. (Examples: in-banner video unit, display banner, rich-media banner, companion banner)

Using “display banner” provides Brave with the same versatility that I suspect the team was aiming for, without requiring additional cognitive load during onboarding and operations. 

Read this entire issue as: “it was easy to jump right in to brave ads” - “receive fewer questions over support channel” - “write one less tooltip” - “one less FAQ item to create”

**Comment by IanKrieger** [comment]
This ad format is no longer relevant for self-serve
