### ISSUE TITLE
Brave Rewards: Self Service Ads

### ISSUE THREAD

**Issue by dlipeles** [brave/ads-ui#337]
A roadmap for our upcoming product, **Brave Rewards: Self Service Ads**, a web application which grants advertisers of any size access to the Brave/BAT Ads Ecosystem. From the web app, advertisers will be able to define objective-based ad campaigns, preview their creatives, and submit ads for approval into the Brave Browser's ads catalog. 

Our roadmap is structured in versions, with 1.0 being limited release to Brave Ad Partners, 2.0 being general release to Brave Ad Partners with limited release to the public, and 3.0 being full general availability. 

#### Brave Ads: Self Service Ads 1.0 

- ✅ Foundational Node.js / React / GraphQL web application hosted at ads.brave.com  
- ✅ Admin functionality for creating / managing / approving ad campaigns 
- ✅ Reporting functionality for advertisers running campaigns, display # impressions, clicks, CTR, conversions etc. 
- ✅ Streamlined ad campaign builder component designed specifically for advertisers 
- ✅ Foundational accounting system providing invoices for advertisers denominated in USD or BAT 
- ✅ Server side enhancements: CPC / CPA pricing, State level marketing, Attributions, Scaling improvements 

#### Brave Ads: Self Service Ads 2.0 

- #### Improve Web App Infra. (Host with S3/CloudFront CDN, Apollo GraphQL Caching, Refactor Codebase)
  - ✅ Host with S3/CloudFront CDN, automated deploys with CodePipeline / CI 
  - ✅ Refactor Admin Dashboard into own repo and host at [admin.ads.brave.com](admin.ads.brave.com)
  - Update Redux Caching Layer on user facing app, use Apollo GraphQL, fix stale session / caching / state issues
  - Host Landing Page directly at [ads.brave.com](ads.brave.com) / [admin.ads.brave.com](admin.ads.brave.com) 
- #### Improve User Registration / Sign-in Flow
  - 🏗️ Replace Google form with in-house designed form
  - Forward large clients to Brave Sales Team , forward mid-size / small clients to account creation & waitlist
  - Improve account registration, forgotten password, activating 2FA, email management
- #### Build User-Facing Components for Editing Live Campaigns 
  - ✅  Develop components for updating campaigns, ad sets, ads & creatives
  - ✅  Develop specialized flows for updating approval based fields (creative text & assets) 
- #### Extend Campaign Creation / Reporting to New Tab Page: Sponsored Image Ads 
  - ✅ Develop new creative type & server infra. for NTP SI campaigns 
  - Develop specialized report generation for NTP SI campaigns 
- #### Improve Ad Campaign Reporting with Advanced View and Insights 
  - ✅ Add date range functionality to campaign insights
  - Add platform, category, geo displays to campaign insights 
  - Add specialized insights report PDF available for download from campaign insights
  - Create advanced reporting section, with custom tables / file export, campaign / ad set / ad / creative comparison 
- #### Improve Brave Ad Ops UX
  - Ensure consistent search, linking, loading, and functionality across admin components 
  - Build functionality for campaign drafts / duplication 
  - Build functionality for batch operations on campaigns 
  - Build functionality for CSV / Script upload into campaign creation 
- #### Add Invoicing / Balance Page to User-Facing Accounts 
  - Develop automated accounting system on server 
  - Build component to display current advertiser balance, payment methods, upcoming payments
  - Build component to display previous invoices, export files, etc. 
- #### Implement Automated Invoicing / Payment Processing 
  - Develop integration with the following payment methods: BAT, Stripe, PayPal
  - Develop scheduled server job to process payments, manage advertiser accounts, notify with emails
- #### Server-Side Enhancements
  - ✅  Develop improved campaign pacing mechanisms & monitoring 
  - ✅ Develop dayparting mechanism with frontend selector 

#### Brave Ads: Self Service Ads 3.0
- Ramp up scale, web3 integrations with BAT, cross platform PWA, etc. ✨

**Comment by namelessperson0** [comment]
Self service ads is consistently being requested by users https://www.reddit.com/r/BATProject/comments/ljeyrn/hey_guys_anyone_know_when_the_self_serve_ad

**Comment by UjCbFwtBayFM** [comment]
Users requesting updates: https://www.reddit.com/r/BATProject/comments/s0vr92/any_self_serve_update/
