### ISSUE TITLE
Self-serve allows saving URLs as http, then URLs are changed to https

### ISSUE THREAD

**Issue by murphyd** [brave/ads-ui#392]
When using self-serve, you can save a creative URL as http. After the campaign is published, the URL is converted to https. 

Expected behavior would be for self-serve to show an error if a user uses a link with http.

Here is a screenshot before publishing a self-serve campaign with http://brave.com:
![image](https://user-images.githubusercontent.com/4502617/85300768-fa7e2b00-b474-11ea-97c5-89f7c5ba5e87.png)

Here is the same creative, after saving:
![image](https://user-images.githubusercontent.com/4502617/85301362-b93a4b00-b475-11ea-8281-e3797a19c96d.png)

This occurred during a recent campaign setup with BSA, with ads Honey - 3, Honey - 4, and Honey -5 all saving as https: https://ads.brave.com/admin/main/users/f94cf83f-7489-4153-9a62-1a2cd5bde321/advertiser/8cfac071-75f8-46ab-9c7f-4f8420d914d7/creative

Slack thread here: https://bravesoftware.slack.com/archives/CJL3G0S95/p1592742837430700

**Comment by IanKrieger** [comment]
Should be resolved
