### ISSUE TITLE
Website URL will not save if there is a space at  the end

### ISSUE THREAD

**Issue by murphyd** [brave/ads-ui#418]
Using the admin panel, when entering the website details under the website URL field, if the URL contains a space at the end it will not save. The save button will say "Saving..." and stay that way until you refresh the page. 

![image](https://user-images.githubusercontent.com/4502617/88950195-4a18f900-d262-11ea-8b20-926998f3bbfa.png)

Ideally, this should show a warning that something is incorrect, or automatically remove the space(s) at the end.

**Comment by iambrianfung** [comment]
https://github.com/brave/ads-admin-dashboard/pull/18/
