### ISSUE TITLE
Adding CTR when mousing over charts in reporting view

### ISSUE THREAD

**Issue by murphyd** [brave/ads-ui#433]
When moving your mouse over the chart under reporting view, it displays Impressions, Clicks, Dismissals, and Landings.

Could CTR be added to this? It would be a quick way to analyze CTR by hour/day/week without having to calculate it manually. 

![image](https://user-images.githubusercontent.com/4502617/91205100-0683a480-e6d3-11ea-987f-d5f85ab3de92.png)

**Comment by dlipeles** [comment]
@murphyd Happy to say this feature is merged in, try clicking on the arrows in the stats boxes, you'll see a dropdown with CTR in it 

<img width="506" alt="Screen Shot 2020-09-17 at 6 17 42 PM" src="https://user-images.githubusercontent.com/4713771/93533993-2ee97200-f912-11ea-950e-5c175ab5ef17.png">
