### ISSUE TITLE
Conversion URL is adding "/" to end if there is no slash.

### ISSUE THREAD

**Issue by murphyd** [brave/ads-ui#453]
We noticed a problem lately where the conversion URL seems to be adding a "/" to the end of the URL. Just caught it in the act. The first screenshot is before saving, and the second is after saving. If the "/" is added, this seems to cause a problem with conversion reporting. 

To work around this, we need to save the ad set details, let it add the slash, remove the slash, and re-save it.

Can this be investigated, please?

![image](https://user-images.githubusercontent.com/4502617/94750509-3407e180-0354-11eb-8394-9cb5c177a953.png)
![image](https://user-images.githubusercontent.com/4502617/94750493-2d796a00-0354-11eb-8819-833d1dba0e31.png)

**Comment by amirsaber** [comment]
This was a request from client to have that enforce / on some urls. Cc: @tmancey

**Comment by tmancey** [comment]
@murphyd Discussed with @amirsaber as the `/` should only be added to `TLD+1` and not the path.
