### ISSUE TITLE
Automatically calculate daily budget for self-serve campaigns

### ISSUE THREAD

**Issue by murphyd** [brave/ads-ui#488]
The self-serve change was suggested by an advertiser testing self-serve:

_I would like to enter a lifetime budget and have the Daily Budget update automatically according to the date-range I've selected, much like exchanges do when you enter the price for the coin and it automatically fills in the amount of coin you're buying or selling. Doing the math manually isn't difficult, of course, but this would be a nice feature that would improve efficiency on my end since I won't have to open another app (calculator) to do the math in order to get an even spread across my begin and end dates._

![image](https://user-images.githubusercontent.com/4502617/98547595-69aebd00-2266-11eb-9843-f81b61d2031f.png)

This makes sense, and should reduce confusion on the advertiser's end. 

As an alternative option, perhaps this could be filled in, but not editable by the advertiser. It would simply show the estimated amount it would spend per day.

**Comment by IanKrieger** [comment]
Done, can revisit if needed
