### ISSUE TITLE
Self-Serve: Ads do not save when CPM field is left blank

### ISSUE THREAD

**Issue by murphyd** [brave/ads-ui#495]
When in self-serve, and doing an advanced order, leaving the pricing field blank under ad set details will cause the campaign to not save:
![image](https://user-images.githubusercontent.com/4502617/99079592-2ae27500-258e-11eb-9a66-cff72dc2a2d9.png)

I tested this with both CPM and CPC. 

After clicking "Publish Campaign" the congratulations screen appears, but the campaign does not appear on either the advertiser's end or in the approval queue on the admin side. 

Creatives that were created during the campaign are setup.

The user should be forced to put in a price (whether CPM or CPC) when building a campaign. If it tries to publish without this, it should show an error stating the pricing info is missing under the ad set details.

**Comment by IanKrieger** [comment]
Should be resolved, please re-open if not
