### ISSUE TITLE
Popup information box indicating success/failure when trying to save 

### ISSUE THREAD

**Issue by murphyd** [brave/ads-ui#537]
I’ve noticed when saving items in the ads server, I’m not presented a success/fail dialog which previously appeared. 

For instance, earlier I tried to save a creative instance as “view” when the ad set was set for CPC. This previously caused a message to come up in the bottom left indicating there was an error. This time, it didn't save, but no indication was given that this failed. 

We should clearly be notified if something succeeded or failed, so we can go back and fix this. I’m assuming this started after the changes done last week. 

There is a "success" dialog that appears on many screens after saving (e.g. campaign, ad sets) and this message appears at the top of the screen. The only way to see it is to press save and scroll to the top. 
![image](https://user-images.githubusercontent.com/4502617/105383904-9fb1db00-5bdf-11eb-905e-d67082f1dd6f.png)

Perhaps this success indication could pop up from the bottom?

For self-serve, this would also be helpful, since we won't leave users guessing if something failed or succeeded.

**Comment by iambrianfung** [comment]
@murphyd how about we keep the top one and put one on the bottom too?
