### ISSUE TITLE
ads.brave.com does not load on iOS (blank page)

### ISSUE THREAD

**Issue by Miyayes** [brave/ads-ui#564]
## Description

On desktop, when visiting `ads.brave.com`, it successfully redirects to `brave.com/brave-ads`. However, on mobile iOS, it will just show a blank page and not complete the redirection.

**Comment by amirsaber** [comment]
observing following in safari
![image](https://user-images.githubusercontent.com/4715448/113219602-aef07d00-924f-11eb-8ef6-421195bc34ec.png)

https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group/51568859

**Comment by iambrianfung** [comment]
Issue arises from `normalize-url` version. 
https://github.com/sindresorhus/normalize-url/issues/105

should point to version 4.
https://github.com/sindresorhus/normalize-url#install
