### ISSUE TITLE
Incorrect user name or password when logging in does not produce an error

### ISSUE THREAD

**Issue by murphyd** [brave/ads-ui#585]
When logging into `ads.brave.com/u/`, inputting an incorrect user name or password does nothing -- does not display an error, failure, etc.

Dev tools shows:
![image](https://user-images.githubusercontent.com/4502617/140088664-edacdd2a-d8ea-4aba-b7f1-d16812c81975.png)

Ideally, an incorrect user name or password should display "The user name or password you have entered is not correct. Please contact your Brave account manager for assistance." Right now there is not an option to do a password reset on the user-end. 

The error should not indicate that the email address is valid, even if it is, and just use the generic error for both a user name and a password failure. 

Also, it seems that hitting error may not do anything after inputting the user name and password. If that's the case, bonus points for adding the function to submit using the enter key.

**Comment by tackley** [comment]
Also applies to `ads-admin`.
