### ISSUE TITLE
Allow only URLs with `https` protocol during campaign creation

### ISSUE THREAD

**Issue by thypon** [brave/ads-ui#607]
# Description

When creating a new campaign, an attacker may use arbitrary protocols to inject `javascript` or OS command link vectors.

# Reproduction Steps

<img width="723" alt="screenshot_2022-04-25_at_16 56 58" src="https://user-images.githubusercontent.com/581115/165117076-3ca4fb82-8549-4f9b-ae03-bf8e6480d099.png">

# Proposed fix

Disallow any URL not employing `https` scheme.

Cc @tackley

**Comment by diracdeltas** [comment]
@tackley this seems like an important security feature, could you take a look?

**Comment by IanKrieger** [comment]
This should be fixed as of: https://github.com/brave/ads-serve/pull/2901
