### ISSUE TITLE
Advertiser Reporting Dashboard: Color Code Campaign Status Indicator

### ISSUE THREAD

**Issue by StephenBass** [brave/ads-ui#617]
We wish to include the same 4-tiered, color status indicator on the advertiser reporting dashboard. Accessing one of the advertiser accounts, you will find this at the dashboard location below
https://ads.brave.com/user/main/campaigns

4 different colors and labels are used to indicate campaign status
Green = Active
Yellow = Daycomplete
Red = Paused
Grey = Past end date & Complete

Currently, the same campaign status indicators are used on the admin dashboard frontend. You can find this below:
Campaign overview https://ads-admin.brave.com/campaigns?format=overview
Campaign pacing https://ads-admin.brave.com/pacing
User campaigns https://ads-admin.brave.com/advertisers/1b630036-6d11-4833-adc3-d31fb8b78bb2/campaigns

This request similar to the original task for admin dashboard status indicator https://github.com/brave/ads-admin-dashboard/issues/368
![image](https://user-images.githubusercontent.com/32347415/182804081-e56fbfda-01b8-4edb-8185-dcdc564e4a01.png)

**Comment by IanKrieger** [comment]
This has been resolved
