### ISSUE TITLE
Validation: Conversion URLs must be the same eTLD+1 as Creative target URL

### ISSUE THREAD

**Issue by iambrianfung** [brave/ads-ui#741]
If Conversion URL is provided, check that it is the same eTLD+1 as the target URL of the creatives provided.
If not, reject the Conversion URL and inform the user.

**Comment by IanKrieger** [comment]
@iambrianfung this would assume that all creatives also have the same `eTLD+1`, is this an expectation as well?

**Comment by murphyd** [comment]
The expectation here would be:
1. the creatives would match the same eTLD+1
2. There should be a larger discussion around conversion URLs. Not all advertisers use the same domain for a conversion URL. For example, some have used a conversion URL located on https://chromewebstore.google.com/, others may use social channels, etc. as a conversion URL.

**Comment by tackley** [comment]
Enforced server-side by https://github.com/brave/ads-serve/issues/3970
