### ISSUE TITLE
Creative management screen

### ISSUE THREAD

**Issue by IanKrieger** [brave/ads-ui#923]
Advertisers can now share creatives between campaigns, need a place to manage these.

**Comment by shubrautt** [comment]
@IanKrieger how can I able to set up a project on my local? how the backend are working for this project? thank you...!!

**Comment by IanKrieger** [comment]
Hi @shubrautt, unfortunately the backend is not available for public development at this time. Hopefully we will be able to make it open in the future for collaboration.

**Comment by shubrautt** [comment]
@IanKrieger okay, thanks for replying.
