### ISSUE TITLE
Changing CPV to CPSV (Cost Per Site Visit)

### ISSUE THREAD

**Issue by murphyd** [brave/ads-ui#955]
- Instead of CPV, the acronym will now be CPSV, which stands for Cost Per Site Visit
- We need to modify instances of "lands" and "10s Visits" to "Site Visits" in the ad server, and report exports, etc. for consistency.

**Comment by murphyd** [comment]
Updated to "Site Visits" per today's conversation.

**Comment by IanKrieger** [comment]
Determined we will not introduce CPSV in self-serve
