### ISSUE TITLE
Add ghost.org consent checkbox to self-serve registration

### ISSUE THREAD

**Issue by IanKrieger** [brave/ads-ui#982]
Add a checkbox where a person can consent to receive emails from brave via ghost.org

**Comment by diracdeltas** [comment]
does this need @PrivacyMatters review?

**Comment by IanKrieger** [comment]
@diracdeltas I see a previous security review with him approving the use of Ghost here: https://github.com/brave/reviews/issues/1009

So my assumption is this is covered under that, as I am using the same setup as brave.com is. Let me know if you disagree.

**Comment by diracdeltas** [comment]
thanks, just to be on the safe side i tagged him as a reviewer

**Comment by PrivacyMatters** [comment]
@diracdeltas no.
