### ISSUE TITLE
Add tooltips in reporting UI for available reporting metrics

### ISSUE THREAD

**Issue by murphyd** [brave/ads-ui#989]
In the reporting UI, we should add tooltips for Impression, Click, Dismissed, etc. with language that matches the following help center article:

https://ads-help.brave.com/campaign-performance/reporting/#available-reporting-metrics-in-brave-ads-manager

cc: @lukaslevert

**Comment by lukaslevert** [comment]
Thanks @murphyd — note for team. Let's just hold on this until the help center is updated with the latest definitions so that we don't have to do it twice. I'll comment on this issue when that's done.

**Comment by lukaslevert** [comment]
Confirming the required changes are live on ads-help.brave.com, and we can proceed with this change when resources permit. CC @murphyd @IanKrieger
