### ISSUE TITLE
Create prospect funnel from existing self-serve customers to purchase NTT and  Search Ads campaigns. 

### ISSUE THREAD

**Issue by murphyd** [brave/ads-ui#992]
Description: 
When a self-serve customer wants to purchase inventory for NTT or Search Ads, we provide them with a journey that puts them on a path toward additional revenue for Brave.

**SCOPE**
- Where the self-serve advertiser selects the ad unit to run in the UI, feature the NTT and Search Ads units as options alongside Notifications and News. 
- If they select NTT they are sent to managed services for a discussion with Sales and AM to upsell and coordinate on NTT.
- If the advertiser is interested in a Search Ads campaign, when they click to choose that campaign type, they are met with a form in the UI that includes qualifying criteria for the advertiser to input. 
- If buyer meets criteria, they are added to a curation queue at ready status for JP to review and greenlight. 
- If they do not meet criteria, they are added to a waitlist that we will connect with when they do meet qualifying criteria in the future. 

Examples of qualifying criteria: 

- Have you run search ads on Google or Bing, in the past 30 days? 
- IF YES: How much did you spend per day (include list of ranges to select from).

**Comment by lukaslevert** [comment]
Hey @IanKrieger - here's a mockup for how I think we could do this: 

<img width="1124" alt="image" src="https://github.com/brave/ads-ui/assets/79997955/c3d052be-b550-471b-859c-14e83c527eaa">

- Include two new "greyed" buttons 
- Use a (!) icon to indicate some kind of alert/warning
- Clicking the ad type brings up the tooltip that informs them the ad unit isn't available for self-managed campaigns.
- Link to "contact sales" goes to ads.brave.com/contact

Bonus: added some "learn more" links to the titles of the different sections, where we can link to specific articles on the help centre throughout the process. WDYT?
